git:
  depth: 1

branches:
  except:
    - /^\d+\.\d+\.\d+$/

os: linux
dist: xenial
group: edge
language: java
jdk:
  - openjdk8

env:
  global:
    - secure: "oEt98tzosYyP4fqK/tzen14TP96BnGpPSN5rhIDWjcrn2Vd4EzcECoCGjJSx55xyOT9YD1+iPbZFwA4rRswZ+EJPmDpU5x+iKnFtOETh0KB0Y1c141BgTQZVPA67bwdKhADVwTMU2S7IkeKM1vFPyxxZ8wWLg4hLT5aOaokbS59qvLVsxglpEvC8w4q5AgeMgaqmRbtiWD4k7m3fN3RKaOKMRTQZ2X41bvrbJ0hNG+oicVl6oJff4Da1nO/a1/eZJar2gtThe3+td5Idt48zniWsyjKRAf2yIgNz/gPQjBo0ibrhiPYJU+LJv1mp4lK7HDPhlJ2EnfUH1BkXwNfMWanvwfTZ9tHJ2CueCqpIO6l97D2Y7rStrx1nl23rmuQEazefUEnRO6ggWZFbJXVyki5ls6zdQ0XSnvX9uo1zCvWO4GE4AW2OEN52ILPpLxsHzCcNee2xRJJ6pkZj19m5grJpyKxMJ34D02qHde58hscY1pbjjrApquDCMCvYKGTQy3lTLdtUb18vVToKcTamz4nOgaK1ySI9hJ1hFlbubBQywiKkP4dTvnnIu7bbYH6yPRGDOuRVpHR5o1OtEPiUMLwRMzcEZcEJ2LJB5hJ48lDPlxZPZe79L9jfkMbyg9VBBjxaCRpvF+lqCi3wX18hBC62NVaT8Rmxv13zYmxH2nw="
    # for updates check developer.android.com/studio#downloads (current 26.1.1)
    - ANDROID_SDK_TOOLS=sdk-tools-linux-4333796.zip

before_install:
  # Decrypt and unpack secrets
  - openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

install:
  ## Android
  # Source: https://travis-ci.community/t/installing-android-dependencies-android-update-sdk-command-not-found/4138/5

  # Download and unzip Android SDK command line tools
  - wget -nv https://dl.google.com/android/repository/$ANDROID_SDK_TOOLS
  - unzip -q $ANDROID_SDK_TOOLS -d $HOME/sdk
  # Set SDK tools path variable and ANDROID_HOME
  - export PATH=$PATH:$HOME/sdk/tools/bin
  - export ANDROID_HOME=$HOME/sdk
  # Create empty config file to prevent sdkmanager warning message
  - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
  # Accept Android licenses for all available packages that have not already been accepted
  - yes | sdkmanager --licenses > /dev/null

  ## Ruby

  # https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html
  # https://github.com/rubygems/rubygems/issues/3068
  - gem update --system 3.0.6
  # Install Bundler
  - gem install bundler -v 2.0.1
  # Install all Ruby dependencies
  - bundle install

before_script:
  # Create dir for gradle settings
  - mkdir -p $HOME/.gradle
  # Disable gradle daemon for current user
  - echo "org.gradle.daemon=false" >> $HOME/.gradle/gradle.properties
  # Set gradle log format to plain
  - echo "org.gradle.console=plain" >> $HOME/.gradle/gradle.properties

script:
  - ./build.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
