# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    gradle(task: "bundleRelease")
    upload_to_play_store(
      track: "production",
      version_code: options[:version_code]
    )
    upload_to_play_store(
      track: "production",
      skip_upload_aab: true,
      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      version_code: options[:version_code]
    )
  end

  desc "Update changelogs of latest release"
  lane :update_changelogs do
    # Source: https://github.com/fastlane/fastlane/issues/15745#issuecomment-567608145
    versions = google_play_track_version_codes(track: "production")
    version_code = versions[0]
    upload_to_play_store(
      track: "production",
      skip_upload_aab: true,
      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      version_code: version_code
    )
  end
end
