# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "bundleRelease")
    upload_to_play_store(track: "production")
    upload_to_play_store(
      track: "production",
      skip_upload_aab: true,
      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Update changelogs"
  lane :update_changelogs do
    upload_to_play_store(
      track: "production",
      skip_upload_aab: true,
      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
